server:
  port: 5003

spring:
  datasource:
    url: jdbc:postgresql://mivecinoappdb.cfflzxsqwkgf.us-east-1.rds.amazonaws.com/postgres
    password: VOY_A_SER_MAFIOSA_6
    username: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: 'Z6DiCRSaNfbwKoLOtIsotbD8UN2this-is-very-secure-Vv7sdq5wo0xmmmFpGaOATGdKQIn8RXh1r1bk19hOTqO'